name: publish

on:
  workflow_dispatch:

jobs:
  publish-hello-docker-image:
    runs-on: ubuntu-latest

    permissions:
      packages: write
      contents: read

    strategy:
      matrix:
        image:
          - name: hardhat_node

    steps:
      - name: Checkout repository
        uses: actions/checkout@v4

      - name: Login to GitHub Container Registry
        uses: docker/login-action@v3
        with:
          registry: ghcr.io
          username: ${{ github.actor }}
          password: ${{ secrets.GITHUB_TOKEN }}

      - name: Build the Docker image
        uses: docker/build-push-action@v5
        with:
          push: true
          context: ./${{ matrix.image.name }}
          tags: ghcr.io/achilleaseconomopoulos/${{ matrix.image.name }}:latest