name: publish

on:
  workflow_dispatch:

jobs:
  publish-hello-docker-image:
    runs-on: ubuntu-latest

    permissions:
      packages: write
      contents: read

    strategy:
      matrix:
        image:
          - name: hardhat_deployer
          - name: kube_monitor
          - name: oasees-ide
          - name: ipfs_node

    steps:
      - name: Checkout repository
        uses: actions/checkout@v4

      - name: Login to GitHub Container Registry
        uses: docker/login-action@v3
        with:
          registry: ghcr.io
          username: ${{ github.actor }}
          password: ${{ secrets.GITHUB_TOKEN }}

      - name: Set up Docker Buildx
        uses: docker/setup-buildx-action@v3

      - name: Build the Docker image
        uses: docker/build-push-action@v5
        with:
          push: true
          context: ./${{ matrix.image.name }}
          platforms: linux/amd64, linux/arm64
          tags: ghcr.io/oasees/${{ matrix.image.name }}:latest